[project]
name = "aug-project5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.1",
    "ffmpeg-python>=0.2.0",
    "grad-cam>=1.5.5",
    "ipykernel>=6.30.1",
    "koreanize-matplotlib>=0.1.1",
    "librosa>=0.11.0",
    "matplotlib>=3.10.5",
    "numpy<2",
    "optuna>=4.5.0",
    "opencv-python>=4.11.0.86",
    "pandas>=2.3.1",
    "protobuf==3.20.3",
    "pydub>=0.25.1",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.9",
    "scikit-learn>=1.7.1",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.1.0",
    "soundfile>=0.13.1",
    "speechrecognition>=3.14.3",
    "streamlit>=1.49.0",
    "tensorboard>=2.20.0",
    "tensorboardx>=2.6.4",
    "torchaudio>=2.8.0",
    "tqdm>=4.67.1",
    "uvicorn>=0.30.0",
]
